version: '3.8'

services:
  # PHP-FPM service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    expose:
      - "9000"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - db

  # Web server (e.g., Nginx) to serve the app
  web:
    image: nginx:latest
    container_name: nginx-web
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - app

  # Database (MySQL example, replace with your actual DB configuration)
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
