name: Build and Push Backend Image to DockerHub

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "h0ussam3" --password-stdin

      # Step 3: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t h0ussam3/te-backend:latest ./laravel-Backend-API

      # Step 4: Push Docker image to DockerHub
      - name: Push Docker Image to DockerHub
        run: |
          docker push h0ussam3/te-backend:latest
